% This file illustrates a quick way to loop over -subplot using an external
% file for IRFs generated by Dynare. 
% Easy to extend to many more variables, if desired.


% This implementation was written by Camilo Marchesini.

% MATLAB_R2019a and subsequent distributions. Backward compatibility untested.

% MIT License
% 
% Copyright (c) 2019 Camilo Marchesini
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.



% Run .mod file
dynare yourmodfile
% Save IRFs associated with the parameterization in yourmodfile.mod with
% interesting_irf=oo_.irfs;

% Load IRFs
load 'interesting_irf';

% Cell array of shocks
shock = {'eps_z'}; % or names of your exo shocks
% Cell array of variables to plot
var_plot = {'y','pi','c'};
% cell array of labels
var_label = {'Output','\pi','Consumption'};

%% Set plot options
%%%%%%%%%%%%%%%%%        
IRF_periods=40;
% American rose
amrose=[1.0 0.01 0.24];    % From http://latexcolor.com/

x0=10;
y0=10;
width=1180;
height=2000;

font = 'Century Schoolbook';
%%%%%%%%%%%%%%%%%
%% begin figure.
hFig = figure('DefaultTextFontName',font,'DefaultAxesFontName',font,'DefaultLineLinewidth',2,'DefaultTextFontSize',12,'Name','Interesting Shock');

% Begin loop.
    for ii=1:length(var_plot)
       for jj=1:length(var_label)
         for kk=1:length(shock)
    subplot(1,3,ii)              % Adapt to number of elements in var_plot 
    hold on
    plot(zeros(IRF_periods,1),'k--','HandleVisibility','off','LineWidth',1); % steady-state level (or stochastic mean for GIRFs)
    plot(0:options_.irf,[0 fprintf('interesting_irf.%s_%s\n', var_plot{ii}, shock{kk})],'-.','Color',amrose);	
    title(strtrim(var_label{jj})); % Strip leading and trailing whitespace
    axis tight;
         end
      end
   end  % Loop end. 
   
 set(gcf,'position',[x0,y0,width,height]);
 % Save Matlab figure.
 savefig('IRF_interesting');
 % Save as .png file.
 print('IRF_interesting','-dpng','-r300');
 % End figure.
 
 % End.