% This file illustrates a quick way to loop over -subplot using an external
% file for IRFs generated by Dynare. 
% It is straightforward to extend to more variables, model comparison, and shock comparison, if desired.


% This implementation was written by Camilo Marchesini.

% MATLAB_R2019a and subsequent distributions. Backward compatibility untested.

% MIT License
% 
% Copyright (c) 2019 Camilo Marchesini
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.



% Run dynare file.
dynare yourmodel
% Save IRFs.
yourmodel_irf=oo_.irfs;
save yourmodel_irf;
% Load.
load('yourmodel_irf');

%% Set plot options
%%%%%%%%%%%%%%%%% 
% Number of IRF periods.
IRF_periods=20;
% American rose.
amrose=[1.0 0.01 0.24];    % From http://latexcolor.com/
% Length.
L=0:options_.irf;

% Size of plot window.
x0=10;
y0=10;
width=1180;
height=2000;
% Select font.
font = 'Century Schoolbook';
%%%%%%%%%%%%%%%%%


%% Begin Figure 1

% Cell array of shocks.
shock = {'_eps_r'};
% Name of exo shocks.
shock_name={'Policy rate shock'}; 
% Cell array of variables to plot.
var_plot = {'r','x','pi'};
% cell array of labels
var_label = char('Policy rate','Output gap','Inflation');
% Scale
scale = [1,1,4]; % Set variables you wish to annualise to 4, e.g. [1,1,4] if you want annualised inflation rate.

% Check.
if isfile('numSubplots.m')
     nsubplots=numSubplots(length(var_plot));
else
     error('Function file numSubplots.m is not in the working directory. Look for the file and move it to this directory to continue. If you do not have it you can download it at https://se.mathworks.com/matlabcentral/fileexchange/26310-numsubplots-neatly-arrange-subplots')
end


% Check.
if length(var_plot)~=length(var_label)
elseif  length(var_plot)~=length(scale)
    error('Number of variables to plot, variable labels, and scale of the variables not all of the same size.')
end

hFig1 = figure('DefaultTextFontName',font,'DefaultAxesFontName',font,'DefaultLineLinewidth',2,'DefaultTextFontSize',12,'Name',shock_name{:});

% Begin loop.
    for ii=1:length(var_plot)
        for kk=1:length(shock)
    subplot(nsubplots(1),nsubplots(2),ii)
    % Uncomment the two lines below if you are applying this code to a nonlinear
    % model.
    % hold on
    % plot(zeros(IRF_periods,1),'k--','HandleVisibility','off','LineWidth',1);
    % % to show steady-state level.
    plot(L,[0 scale(ii)*eval(['yourmodel_irf.' var_plot{1,ii}, shock{1,kk}])],'-.','Color',amrose);	
    title(deblank(var_label(ii,:)))
    axis tight;
           
        end
    end
 % Loop end.
   
 % Set position.
 set(gcf,'position',[x0,y0,width,height]);
 % Uncomment the following lines to save.
 
 % Save Matlab figure.
 % savefig('IRF_yourmodel_eps_r');
 % Save as .png file.
 % print('IRF_yourmodel_eps_r','-dpng','-r300');
 % End figure.
 
% End
